import { useEffect, useState, useSyncExternalStore, type ChangeEvent } from 'react';
import { DEFAULT_PACKS, PACKS } from './prompts';
import { activePlayers, isMatchOver, scoringOwner, type Mode } from './game';
import { Artwork } from './Artwork';
import { AvatarPicker } from './AvatarPicker';
import { GameSettings, STYLE_LABELS } from './GameSettings';
import { Leaderboard } from './Leaderboard';
import { AVATARS, CUSTOM, musicScene } from './customization';
import { GameController } from './controller';
import { BUILD, roomLink } from './room';
import { isMuted, isMusicEnabled, musicStatus, play, retryMusic, setMuted, setMusicEnabled, startMusic, stopMusic, setMusicScene, subscribeMusic } from './sound';
import { JoinQr } from './JoinQr';
import { Display } from './Display';
import { RevealStage } from './RevealStage';
import { Imprint, Privacy } from './Legal';
import { REACTION_LABELS } from './party';
import { ReactionBar } from './ReactionBar';
import { Lobby } from './Lobby';
import './style.css';
import './lobby.css';
const nameKey='delete-this-name';
function currentRoute(){const hash=location.hash.slice(1).split('?')[0];return ['/spiel','/datenschutz','/info','/impressum'].includes(hash)?hash:'/';}
function App(){
 const [controller]=useState(()=>new GameController());
 const {game,role,you,roomCode,hostKey,busy,status,error,countdown,images,requests,stage,diagnostic,check,online,progress,reaction,autoReveal}=useSyncExternalStore(controller.subscribe,controller.snapshot);
 const musicProblem=useSyncExternalStore(subscribeMusic,musicStatus);
 const debug=import.meta.env.DEV||new URLSearchParams(location.search).get('debug')==='1';
 const [route,setRoute]=useState(currentRoute),[mute,setMute]=useState(isMuted()),[music,setMusic]=useState(isMusicEnabled());
 const [name,setName]=useState(()=>{try{return localStorage.getItem(nameKey)??'';}catch{return '';}});
 const [avatar,setAvatar]=useState(AVATARS[0]??''),[joinCode,setJoinCode]=useState(''),[invitedHostKey,setInvitedHostKey]=useState('');
 const [mode,setMode]=useState<Mode>('PARTY'),[displayOnly,setDisplayOnly]=useState(false),[packs,setPacks]=useState<string[]>(DEFAULT_PACKS),[text,setText]=useState('');
 useEffect(()=>{document.title=`${CUSTOM.brand} – Foto-Partyspiel`;},[]);
 useEffect(()=>{const change=()=>{setRoute(currentRoute());const query=new URLSearchParams(location.hash.split('?')[1]??'');if(query.get('code'))setJoinCode(query.get('code')!);setInvitedHostKey(query.get('host')??'');};change();window.addEventListener('hashchange',change);return ()=>{window.removeEventListener('hashchange',change);controller.leave();stopMusic();};},[controller]);
 useEffect(()=>{if(!status||busy||!game)return;const timer=setTimeout(()=>controller.setStatus(''),4500);return ()=>clearTimeout(timer);},[status,busy,game,controller]);
 useEffect(()=>{setMusicScene(musicScene(game));if(role&&route==='/spiel')startMusic();else stopMusic();},[game?.phase,game?.round,game?.roundLimit,role,route]);
 useEffect(()=>setText(''),[game?.roundId,game?.phase]);
 const remember=()=>{try{localStorage.setItem(nameKey,name.trim().slice(0,30));}catch{/* optional */}};
 const startHost=()=>{remember();play('button');startMusic();void controller.create(name,mode,mode==='PARTY'&&displayOnly,avatar);};
 const startGuest=()=>{remember();play('button');startMusic();void controller.join(name,joinCode,'PLAYER',invitedHostKey||undefined,avatar);};
 const leave=()=>{controller.leave();stopMusic();location.hash='#/spiel';};
 const selectPhoto=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];event.target.value='';if(file)await controller.submit(file);};
 const beginRound=()=>controller.begin(packs);
 const copy=async(value:string)=>{try{await navigator.clipboard.writeText(value);controller.setStatus('Kopiert!');play('button');}catch{controller.fail(new Error('Bitte den Code markieren und kopieren.'));}};
 const me=game?.players.find(p=>p.id===you),host=role==='HOST',spectator=!!me?.spectator;
 const active=game?activePlayers(game):[],hasSubmitted=!!game?.photos.some(p=>p.ownerId===you),voted=!!game?.votes[you];
 const remoteReady=game?.mode!=='REMOTE'||host||game.photos.every(photo=>!!images[photo.id]);
 const finished=!!game&&isMatchOver(game),assignedPhoto=game?.photos.find(p=>p.id===game.assignments[you]);
 const textSubmitted=game?.phase==='write'?!!game.suggestions[you]:!!assignedPhoto?.caption;
 const packChooser=game&&(game.style==='CLASSIC'||(game.style==='MIX'&&game.mixStyles.includes('CLASSIC')))&&<div className="pack-wrap"><h2>Prompt-Packs <span className="pack-count">{packs.length} ausgewählt</span></h2><div className="pack-list">{PACKS.map(pack=><button key={pack.id} title={`${pack.description} · ${pack.prompts.length} Prompts`} aria-pressed={packs.includes(pack.id)} className={`pack-card ${packs.includes(pack.id)?'selected':''}`} disabled={countdown>0} onClick={()=>{setPacks(current=>current.includes(pack.id)?current.filter(id=>id!==pack.id):[...current,pack.id]);play('button');}}><span className="pack-icon">{pack.icon}</span><strong>{pack.title}{pack.adult?' · 18+':''}</strong><span>{packs.includes(pack.id)?'✓':'+'}</span></button>)}</div><p className="fine">After Dark ist standardmäßig aus. Nur mit Erwachsenen aktivieren.</p></div>;
 const needsPacks=game&&(game.style==='CLASSIC'||(game.style==='MIX'&&game.mixStyles.includes('CLASSIC')));
 const shareControls=<><div className="lobby-code">{roomCode.slice(0,5)} {roomCode.slice(5)}</div><button className="small" onClick={()=>void copy(roomCode)}>Code kopieren</button><button className="small" disabled={busy||!hostKey} onClick={()=>void copy(roomLink(roomCode,location,false,hostKey))}>Einladungslink kopieren</button>{hostKey&&<details className="invite-qr"><summary>QR-Code zeigen</summary><JoinQr link={roomLink(roomCode,location,false,hostKey)}/></details>}</>;
 return <div className="app" style={{'--accent':CUSTOM.theme.accent,'--ink':CUSTOM.theme.ink} as React.CSSProperties}>
 <div className="confetti" aria-hidden="true">✦ ★ ✿ ✦ ★ ✿ ✦ ★</div>
 <header><a className="brand" href="#/">{CUSTOM.brand}<Artwork name="camera"/></a><nav><a href="#/spiel">Spiel</a><a href="#/datenschutz">Datenschutz</a><a href="#/info">Info</a></nav><button className="music-toggle" aria-label={music?'Musik ausschalten':'Musik einschalten'} onClick={()=>{setMusicEnabled(!music);setMusic(!music);play('button');}}>{music?'🎵':'🎼'}</button><button className="mute" aria-label={mute?'Ton einschalten':'Ton ausschalten'} onClick={()=>{setMuted(!mute);setMute(!mute);if(mute)play('button');}}>{mute?'🔇':'🔊'}</button></header>
 <main>
 {route==='/'&&<section className="hero panel"><div className="sticker">EURE GALERIE<br/>STEHT VOR GERICHT!</div><h1>{CUSTOM.brand.split(/\s+/).slice(0,-1).join(' ')}<br/><em>{CUSTOM.brand.split(/\s+/).at(-1)}</em></h1><p>Foto finden. Anonym lachen. Abstimmen. Bereuen.</p><a className="button giant" href="#/spiel">JETZT SPIELEN</a><p className="fine">2–20 Personen · ohne Account · Fotos zwischen euren Geräten</p></section>}
 {route==='/datenschutz'&&<Privacy/>}{route==='/impressum'&&<Imprint/>}
 {route==='/info'&&<section className="panel prose"><h1>So spielt ihr</h1><ol><li>Entscheidet: Fotos auf jedem Handy oder gemeinsam auf dem Bildschirm des Hosts? Beim gemeinsamen Bildschirm kann das Host-Gerät auch nur die Show steuern.</li><li>Link teilen. Der Host prüft die Beitrittsanfragen und lässt seine Freunde hinein.</li><li>Wählt 3, 5 oder 10 Runden und euren Modus: Klassisch, Eigene Prompts, Reverse oder einen Mix.</li><li>Der Prompt hat zuerst seinen Auftritt. Danach sucht ihr ein Foto. Reverse beginnt mit Fotos; anschließend schreibt jeder einen Text zum zufällig zugeteilten Foto eines anderen.</li><li>Die Show enthüllt die Einreichungen nacheinander. Jede erhaltene Stimme gibt einen Punkt. Optional gibt es einen Bonuspunkt für den Rundensieg.</li></ol><p><strong>Prompt passt nicht?</strong> Eine echte Mehrheit kann ihn bis zu dreimal pro Runde austauschen. Bereits eingereichte Fotos werden dabei gelöscht.</p><p><strong>Ein Gerät fällt aus?</strong> Die anderen spielen weiter. Der Host kann Einreichungen schließen, die Abstimmung beenden oder die Runde ohne Punkte überspringen. Geöffnete Tabs versuchen sich wieder zu verbinden.</p><p><strong>Gemeinsamer Bildschirm:</strong> Bis zu 20 Spieler. Die Show-Fotos bleiben auf dem Host-Gerät. Nur bei Reverse erhält ein Spieler zusätzlich das ihm zugeteilte Foto.</p><p><strong>Jeder auf seinem Handy:</strong> Bis zu 8 Spieler. Jeder erhält die enthüllten Fotos auf seinem Gerät.</p>{CUSTOM.credits.length>0&&<details><summary>Musik- und Grafiknachweise</summary><ul>{(CUSTOM.credits as {title:string;author:string;license:string;url:string}[]).map((credit,i)=><li key={i}><a href={credit.url} target="_blank" rel="noreferrer">{credit.title}</a> · {credit.author} · {credit.license}</li>)}</ul></details>}<a className="button" href="#/spiel">Zum Spiel</a></section>}
 {route==='/spiel'&&<section className="game-layout">
 {!role&&<div className="panel"><span className="eyebrow">SPIELSTART</span><h1>Wer bist du?</h1><label className="field">Dein Name<input maxLength={30} value={name} onChange={e=>setName(e.target.value)} placeholder="Dein Name"/></label><AvatarPicker value={avatar} onChange={setAvatar}/><div className="two-col"><div className="option"><h2><Artwork name="camera"/> Spiel erstellen</h2><p>Wie wollt ihr die Fotos sehen?</p><div className="mode-row"><button aria-pressed={mode==='PARTY'} className={mode==='PARTY'?'selected':''} onClick={()=>setMode('PARTY')}>Gemeinsamer Bildschirm</button><button aria-pressed={mode==='REMOTE'} className={mode==='REMOTE'?'selected':''} onClick={()=>setMode('REMOTE')}>Jeder auf seinem Handy</button></div><p className="fine">{mode==='PARTY'?'Bis zu 20 Spieler. Dieses Gerät zeigt die Fotos, die anderen reichen per Handy ein und stimmen dort ab.':'Bis zu 8 Spieler. Alle Fotos und die Show erscheinen auf jedem Gerät.'}</p>{mode==='PARTY'&&<label className="inline-choice"><input type="checkbox" checked={displayOnly} onChange={e=>setDisplayOnly(e.target.checked)}/> Dieses Gerät ist nur Bildschirm und Spielleitung</label>}{mode==='PARTY'&&displayOnly&&<p className="fine">Du spielst auf diesem Gerät nicht mit. Zum Mitspielen öffne den Einladungslink auf deinem Handy. Es ist kein zusätzlicher Display-Beitritt nötig.</p>}<button className="button" disabled={busy} onClick={startHost}>SPIEL ERSTELLEN</button></div><div className="option"><h2><Artwork name="ticket"/> Mitspielen</h2><p>Öffne den Einladungslink oder gib den Lobbycode ein.</p><label className="field">Lobbycode<input className="code-input" maxLength={300} value={joinCode} onChange={e=>setJoinCode(e.target.value)} placeholder="ABCDE FG234" autoCapitalize="characters" autoComplete="off"/></label><button className="button pink" disabled={busy||!joinCode.trim()} onClick={startGuest}>BEITRETEN</button></div></div></div>}
 {host&&game?.phase==='lobby'&&<Lobby game={game} host you={you} avatar={avatar} chooseAvatar={path=>void controller.chooseAvatar(path)} remove={controller.remove} share={shareControls} settings={<GameSettings game={game} disabled={countdown>0} configure={controller.configure} chooseRounds={controller.chooseRounds}>{packChooser}</GameSettings>} start={<button className="button green" disabled={active.length<2||countdown>0||(!!needsPacks&&!packs.length)} onClick={beginRound}>{countdown?`START IN ${countdown}`:'PARTIE STARTEN'}</button>} reactions={game.reactionsEnabled&&<ReactionBar lobby disabled={!online||countdown>0} react={emoji=>void controller.react(emoji)}/>}/>}
 {host&&requests.length>0&&<div className="panel admission-panel"><section className="admissions"><h2>Wer klopft an?</h2><p className="fine">Nur Freunde freigeben. Vergleicht die Prüfkennung.</p>{requests.map(r=><div className="request" key={r.id}><div><strong>{r.name}</strong><br/><small>Prüfkennung: {r.check}</small></div><button className="button green" onClick={()=>controller.approve(r.id,true)}>Akzeptieren</button><button className="small" onClick={()=>controller.approve(r.id,false)}>Ablehnen</button></div>)}</section></div>}
 {(role==='PLAYER'||role==='DISPLAY')&&!game&&<div className="panel center"><span className="eyebrow">VERBINDUNG</span><Artwork name="ticket" className="connecting-art"/><h1>{stage==='approval'?'Der Host ist dran!':stage==='connected'?'Spielstand laden …':stage==='connecting'?'Verbinde eure Geräte …':'Lobby suchen …'}</h1><p>{status}</p>{check&&<p>Deine Prüfkennung: <strong>{check}</strong></p>}<p className="fine">Beide Geräte geöffnet lassen. Der Host muss dich freigeben.</p><button className="small" onClick={leave}>Abbrechen</button></div>}
 {role==='PLAYER'&&game?.phase==='lobby'&&<Lobby game={game} host={false} you={you} avatar={avatar} chooseAvatar={path=>void controller.chooseAvatar(path)} remove={()=>{}} share={null} settings={null} start={null} reactions={game.reactionsEnabled&&<ReactionBar lobby disabled={!online||countdown>0} react={emoji=>void controller.react(emoji)}/>}/>}
 {role==='DISPLAY'&&game&&<Display game={game} images={images} code={roomCode} hostKey={hostKey}/>}
 {role!=='DISPLAY'&&game&&game.phase!=='lobby'&&<div className="panel round"><div className="round-top"><span className="eyebrow">RUNDE {game.round} / {game.roundLimit} · {STYLE_LABELS[game.roundStyle]}</span><span className="pill">{game.mode==='PARTY'?'Gemeinsam':'Eigene Handys'}</span></div>{!finished&&!['write','caption'].includes(game.phase)&&<h1 className="prompt" key={`${game.roundId}-prompt`}>{game.prompt}</h1>}
 {game.phase==='prompt'&&<div className="prompt-intro center"><Artwork name="ticket" className="stage-art"/><h2>Erst lesen. Dann Beweise suchen.</h2><p>Die Fotoauswahl öffnet sich gleich …</p><div className="reading-timer" key={game.roundId}/>{host&&<button className="small" onClick={controller.closeStage}>Fotoauswahl öffnen</button>}</div>}
 {['prompt','submit'].includes(game.phase)&&game.roundStyle!=='REVERSE'&&!spectator&&<div className="prompt-skip"><button className="small" disabled={!online||busy||game.promptSkips>=3||game.skipVotes.includes(you)} onClick={()=>void controller.skipPrompt()}>{game.skipVotes.includes(you)?'Für neuen Prompt gestimmt':'Prompt passt nicht'}</button><span>{game.skipVotes.length}/{Math.floor(active.length/2)+1} für Mehrheit · {3-game.promptSkips} Wechsel übrig</span></div>}
 {(game.phase==='write'||game.phase==='caption')&&<div className="center text-stage"><h2>{game.phase==='write'?'Jetzt seid ihr die Redaktion.':'Mach dieses Foto zum Meme.'}</h2>{spectator?<p>Die Spieler schreiben ihre Texte auf den Handys …</p>:<>{game.phase==='caption'&&(assignedPhoto?images[assignedPhoto.id]?<img className="caption-photo" src={images[assignedPhoto.id]} alt="Dein zufällig zugeteiltes Foto"/>:<p>Dein Foto kommt gleich … <button className="small" onClick={()=>void controller.retry()}>Erneut laden</button></p>:<p>Du hast in dieser Runde kein Foto eingereicht und setzt beim Texten aus.</p>)}{!textSubmitted&&(game.phase==='write'||(assignedPhoto&&images[assignedPhoto.id]))?<><label className="field">{game.phase==='write'?'Ein lustiger Prompt für alle':'Deine Bildunterschrift'}<textarea className="creative-text" value={text} maxLength={250} onChange={e=>setText(e.target.value)} placeholder={game.phase==='write'?'Das Foto, das …':'POV: …'}/></label><button className="button green" disabled={busy||!online||text.trim().length<(game.phase==='write'?5:3)} onClick={()=>void controller.sendText(text)}>TEXT EINREICHEN</button></>:textSubmitted&&<p className="success">Dein Text ist drin!</p>}</>}{host&&<p>{game.phase==='caption'?game.photos.filter(p=>p.caption).length:Object.keys(game.suggestions).length} Texte angekommen</p>}</div>}
 {game.phase==='submit'&&<div className="center"><h2>{spectator?'Die Galerie wird durchsucht …':game.roundStyle==='REVERSE'?'Such ein Foto mit Meme-Potenzial':'Such das passende Foto'}</h2>{!spectator&&<><p>{game.roundStyle==='REVERSE'?'Ein anderer Spieler schreibt danach einen Text zu deinem Foto.':'Wähle ein Bild aus deiner Galerie.'}</p>{!hasSubmitted&&!busy&&online&&<label className="button file-button"><Artwork name="camera"/> FOTO AUSWÄHLEN<input type="file" accept="image/*" onChange={e=>void selectPhoto(e)}/></label>}{hasSubmitted&&<p className="success">Foto eingereicht!</p>}</>}{busy&&<div className="transfer-progress"><p>{status||'Foto wird verarbeitet …'}</p><progress max={100} value={progress} aria-label="Fotoübertragung"/><small>{progress}%</small></div>}<p>{game.photos.length}/{active.length} Fotos eingereicht</p></div>}
 {game.phase==='reveal'&&<RevealStage game={game} images={images} host={host} busy={busy} auto={autoReveal} next={()=>void controller.advanceReveal()}/>}
 {game.reactionsEnabled&&['reveal','vote'].includes(game.phase)&&(!spectator||host)&&<ReactionBar disabled={!online} react={emoji=>void controller.react(emoji)}/>}
 {game.phase==='vote'&&<div><h2>{spectator?'Stimmt jetzt auf euren Handys ab!':'Was gewinnt?'}</h2><p>{game.mode==='PARTY'&&!host?'Schau auf den gemeinsamen Bildschirm und wähle die Nummer.':'Eine Stimme pro Person. Jede erhaltene Stimme gibt einen Punkt.'} {game.roundStyle==='REVERSE'?'Dein eigener Text ist für dich gesperrt.':'Dein eigenes Foto ist für dich gesperrt.'}</p>{!remoteReady&&<p>Fotos werden noch übertragen …</p>}<div className={`photo-grid ${game.mode==='PARTY'&&!host?'party-vote':''}`}>{game.photos.map((photo,index)=><div className="photo-card" key={photo.id}><div className="photo-frame">{(host||game.mode==='REMOTE')&&images[photo.id]?<img src={images[photo.id]} alt={`Anonymes Foto ${index+1}`}/>:<span>{index+1}</span>}</div><strong>FOTO {index+1}</strong>{photo.caption&&<p className="photo-caption">{photo.caption}</p>}{!spectator&&<button disabled={voted||busy||!online||scoringOwner(photo)===you||!remoteReady} onClick={()=>void controller.vote(photo.id)}>{scoringOwner(photo)===you?'Deine Einreichung':voted?'Stimme abgegeben':'Dafür stimmen'}</button>}</div>)}</div><p className="center">{Object.keys(game.votes).length}/{active.length} Stimmen</p></div>}
 {host&&!['lobby','result'].includes(game.phase)&&<div className="host-round-controls"><details><summary>Spielleitung: Runde hängt?</summary><p className="fine">Einreichungen vorzeitig schließen oder ohne Punkte überspringen. Fehlende Geräte blockieren die Show nicht.</p>{['write','submit','caption','vote'].includes(game.phase)&&<button className="small" disabled={busy} onClick={controller.closeStage}>{game.phase==='vote'?'Mit vorhandenen Stimmen auswerten':game.phase==='write'?'Vorhandenen Prompt wählen':game.phase==='submit'&&game.roundStyle==='REVERSE'?'Fotos zuteilen':'Mit vorhandenen Einreichungen weiter'}</button>}<button className="small skip-round" onClick={controller.skipCurrentRound}>Runde ohne Punkte überspringen</button></details></div>}
 {game.phase==='result'&&<div className="center"><Leaderboard game={game}/>{host&&(finished?<button className="button green" onClick={()=>controller.rematch()}>REVANCHE</button>:<><p className="fine round-recap">{game.roundLimit-game.round} {game.roundLimit-game.round===1?'Runde übrig':'Runden übrig'} · {STYLE_LABELS[game.style]}</p><button className="button green" disabled={countdown>0||active.length<2||(!!needsPacks&&!packs.length)} onClick={beginRound}>{countdown?`START IN ${countdown}`:'NÄCHSTE RUNDE'}</button><details><summary>Weitere Freunde einladen</summary>{shareControls}</details></>)}{role==='PLAYER'&&<p>{finished?'Zeit für eine Revanche?':'Warte auf die nächste Runde …'}</p>}</div>}
 </div>}
 {!finished&&game?.players.some(p=>!p.connected)&&<div className="connection-warning">Ein Gerät ist offline. Die anderen können weiterspielen.{host&&game.players.filter(p=>!p.connected).map(p=><button className="small" key={p.id} onClick={()=>controller.remove(p.id)}>{p.name} entfernen</button>)}</div>}
 {!online&&<p className="connection-warning" role="alert">Verbindung wird wiederhergestellt … <button className="small" onClick={()=>void controller.retry()}>Erneut verbinden</button></p>}{role&&<button className="small leave" onClick={leave}>Spiel verlassen</button>}
 </section>}
 {status&&game&&route==='/spiel'&&<div className="toast" role="status">{status}</div>}
 {musicProblem&&role&&route==='/spiel'&&<div className="toast music-status" role="status">{musicProblem}{musicProblem.includes('konnte')&&<button className="small" onClick={retryMusic}>Erneut laden</button>}</div>}
 {error&&route==='/spiel'&&<div className="error" role="alert">{error}<button className="small" onClick={()=>void controller.retry()}>Erneut versuchen</button><button aria-label="Meldung schließen" onClick={controller.clearError}>×</button></div>}
 {debug&&route==='/spiel'&&diagnostic&&<details className="diagnostics"><summary>Verbindungsdiagnose</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{diagnostic}</pre></details>}
 {reaction&&route==='/spiel'&&<div key={reaction.id} className="reaction-pop" role="status">{reaction.emoji}<small>{REACTION_LABELS[reaction.emoji]}</small></div>}
 {countdown>0&&<div className="countdown-overlay" role="status" aria-live="assertive"><p>Bereit für schlechte Entscheidungen?</p><strong key={countdown}>{countdown}</strong></div>}
 </main><footer>{CUSTOM.brand} ✦ {CUSTOM.tagline}<div className="footer-links"><a href="#/info">Spielregeln</a><a href="#/datenschutz">Datenschutz</a><a href="#/impressum">Impressum</a></div>{debug&&<small>Version {BUILD}</small>}</footer>
 </div>;
}
export default App;
