import { useEffect, useState, useSyncExternalStore, type ChangeEvent } from 'react';
import { CATEGORIES, type Category } from './prompts';
import type { Mode } from './game';
import { GameController } from './controller';
import { BUILD, parseTurnConfig, roomLink } from './room';
import { isMuted, isMusicEnabled, play, setMuted, setMusicEnabled, startMusic, stopMusic } from './sound';
import './style.css';

const nameKey='delete-this-name';
function currentRoute() {const hash=location.hash.slice(1).split('?')[0];return ['/spiel','/datenschutz','/info'].includes(hash)?hash:'/';}
function App() {
  const [controller]=useState(()=>new GameController());
  const {game,role,you,roomCode,busy,status,error,countdown,images,requests,stage,diagnostic,check,online,progress}=useSyncExternalStore(controller.subscribe,controller.snapshot);
  const [route,setRoute]=useState(currentRoute);
  const [mute,setMute]=useState(isMuted());
  const [music,setMusic]=useState(isMusicEnabled());
  const [name,setName]=useState(()=>{try{return localStorage.getItem(nameKey)??'';}catch{return '';}});
  const [joinCode,setJoinCode]=useState('');
  const [turnText,setTurnText]=useState('');
  const [mode,setMode]=useState<Mode>('party');
  const [categories,setCategories]=useState<Category[]>(['Normal','Freunde','Chaos','Roast','Dating','Party','Schule']);
  useEffect(()=>{
    const change=()=>{setRoute(currentRoute());const code=new URLSearchParams(location.hash.split('?')[1]??'').get('code');if(code)setJoinCode(code);};
    change();window.addEventListener('hashchange',change);
    return ()=>{window.removeEventListener('hashchange',change);controller.leave();stopMusic();};
  },[controller]);
  const remember=()=>{try{localStorage.setItem(nameKey,name.trim().slice(0,24));}catch{/* optional */}};
  const startHost=()=>{try{const turn=parseTurnConfig(turnText);setTurnText('');remember();play('button');startMusic();void controller.create(name,mode,turn);}catch(e){controller.fail(e);}};
  const startGuest=async(input:string)=>{try{const turn=parseTurnConfig(turnText);setTurnText('');remember();play('button');startMusic();await controller.join(name,input,turn);}catch(e){controller.fail(e);}};
  const leave=()=>{controller.leave();stopMusic();location.hash='#/spiel';};
  const selectPhoto=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];event.target.value='';if(file)await controller.submit(file);};
  const vote=(id:string)=>void controller.vote(id);
  const beginRound=()=>controller.begin(categories);
  const copy=async(value:string)=>{try{await navigator.clipboard.writeText(value);controller.setStatus('Kopiert!');play('button');}catch{controller.fail(new Error('Bitte den Code markieren und kopieren.'));}};
  const toggleCategory=(category:Category)=>{setCategories(current=>current.includes(category)?current.filter(c=>c!==category):[...current,category]);play('button');};
  const me=game?.players.find(p=>p.id===you);
  const hasSubmitted=!!game?.photos.some(p=>p.ownerId===you);
  const voted=!!game?.votes[you];
  const remoteReady=game?.mode!=='remote'||role==='host'||game.photos.every(photo=>!!images[photo.id]);
  const winner=game?.players.find(p=>p.id===game.winnerId);
  return <div className="app">
    <div className="confetti" aria-hidden="true">✦ ★ ✿ ✦ ★ ✿ ✦ ★</div>
    <header><a className="brand" href="#/">DELETE THIS! <span>📸</span></a><nav><a href="#/spiel">Spiel</a><a href="#/datenschutz">Datenschutz</a><a href="#/info">Info</a></nav><button className="music-toggle" aria-label={music ? 'Musik ausschalten' : 'Musik einschalten'} title={music ? 'Musik ausschalten' : 'Musik einschalten'} onClick={() => {setMusicEnabled(!music); setMusic(!music); play('button');}}>{music ? '🎵' : '🎼'}</button><button className="mute" aria-label={mute ? 'Ton einschalten' : 'Ton ausschalten'} onClick={() => {setMuted(!mute); setMute(!mute); if(mute) play('button');}}>{mute ? '🔇' : '🔊'}</button></header>
    <main>
      {route === '/' && <section className="hero panel"><div className="sticker">DAS FOTO-CHAOS<br/>MIT DEINEN LEUTEN!</div><h1>DELETE<br/><em>THIS!</em></h1><p>Prompt lesen. Peinliches Foto finden. Anonym lachen. Abstimmen. Bereuen.</p><a className="button giant" href="#/spiel">JETZT SPIELEN ✨</a><p className="fine">2–8 Personen · ohne Account · Fotos bleiben zwischen euren Geräten</p></section>}
      {route === '/datenschutz' && <section className="panel prose"><h1>Datenschutz 🔒</h1><p>Delete This! benötigt keine Accounts. Es gibt keine Analytics, kein Tracking und keine KI-Auswertung. Die Musik und Sounds werden lokal per Web Audio API erzeugt.</p><p>Deine ausgewählten Fotos werden auf deinem Gerät per Canvas verkleinert und neu encodiert. Dabei werden Metadaten wie EXIF und GPS nicht übernommen. Die Originaldatei wird nicht übertragen. Spielbilder bleiben nur vorübergehend im Arbeitsspeicher und werden nach Rundenende oder beim Verlassen aus der App entfernt. Fotos werden nicht gespeichert, auch nicht im Browser-Speicher oder Service-Worker-Cache.</p><p>Für den zehnstelligen Lobbycode nutzt die App mehrere öffentliche MQTT-Broker zur kurzzeitigen, verschlüsselten Vermittlung der WebRTC-Verbindungsdaten. Diese Broker und öffentliche STUN-Dienste können technisch notwendige Verbindungsdaten wie IP-Adressen sehen, erhalten über die App aber keine Fotos oder Spielinhalte. Es gibt dafür keine App-Datenbank und keinen Account.</p><p>Spielnachrichten und Fotos laufen verschlüsselt über WebRTC zwischen den Geräten. Bei optional eingegebenen TURN-Zugangsdaten kann WebRTC einen TURN-Dienst als Transportweg verwenden, falls eine direkte Verbindung durch Mobilfunk, Router oder Firewall blockiert wird. Der Dienst leitet bereits verschlüsselte Pakete weiter, kann deren Inhalt nicht lesen und verarbeitet technisch notwendige Verbindungs- und Verkehrsdaten. TURN-Daten werden nur für die aktuelle Sitzung im Arbeitsspeicher verwendet und nicht gespeichert. Die App lädt Fotos nicht in einen abrufbaren Speicher und richtet keine Datenbank ein.</p><p>Beim normalen Aufruf der Website erhält der Hostinganbieter technisch notwendige Verbindungsdaten, etwa IP-Adresse und Abrufzeit. Details zu dessen Verarbeitung stehen in dessen Datenschutzhinweisen. Der gespeicherte Anzeigename liegt ausschließlich in deinem Browser und kann über die Browserdaten gelöscht werden. Die App speichert keine Fotos.</p></section>}
      {route === '/info' && <section className="panel prose"><h1>So funktioniert’s 🎉</h1><ol><li>Eine Person erstellt das Spiel und wählt Party Mode oder Remote Mode.</li><li>Der Host zeigt den zehnstelligen Lobbycode. Alle Freunde geben ihn ein oder öffnen den Einladungslink.</li><li>Der Host prüft eure Prüfkennung und gibt euch frei. Zwischen den Runden gibt es keine weiteren Codes.</li><li>Prompt lesen, eigenes Foto auswählen, anonym abstimmen. Für den Rundensieg gibt es einen Punkt.</li></ol><p><strong>Party Mode:</strong> Alle sehen die Fotos gemeinsam auf dem Gerät des Hosts. Auf den Handys erscheinen Prompt und Abstimmknöpfe.</p><p><strong>Remote Mode:</strong> Der Host verteilt die verkleinerten Fotos über verschlüsseltes WebRTC; alle sehen sie auf dem eigenen Gerät.</p><p>Mindestens zwei Geräte sind nötig. Mehrere öffentliche Vermittlungsdienste helfen beim Finden der Lobby. WebRTC versucht zuerst eine direkte Verbindung. Bei blockierenden Netzen kann auf beiden Geräten ein eigener, kurzzeitig gültiger TURN-Zugang eingegeben werden.</p><a className="button" href="#/spiel">Zum Spiel →</a></section>}
      {route === '/spiel' && <section className="game-layout">
        {!role && <div className="panel"><span className="eyebrow">SPIELSTART 🎲</span><h1>Wer bist du?</h1><label className="field">Dein Name<input maxLength={24} value={name} onChange={e=>setName(e.target.value)} placeholder="z. B. Chaos-Chris"/></label><details className="turn-settings"><summary>🛠️ Verbindung zwischen getrennten Netzen (TURN)</summary><p>Falls die direkte Verbindung scheitert: Auf beiden Geräten vor dem Start kurz gültige TURN-Daten eingeben. Diese erhältst du von einem TURN-Anbieter; sie werden nur für diese Sitzung genutzt.</p><label className="field">TURN-Konfiguration als JSON<input type="password" maxLength={2000} autoComplete="off" value={turnText} onChange={e=>setTurnText(e.target.value)} placeholder={'{"urls":"turns:relay.example:443","username":"…","credential":"…"}'}/></label><p className="fine">Keine Zugangsdaten im Einladungslink oder Repository veröffentlichen.</p></details><div className="two-col"><div className="option"><h2>🎤 Spiel erstellen</h2><p>Du bekommst einen kurzen Lobbycode. Freunde öffnen deinen Einladungslink. Du bestätigst, wer mitspielen darf.</p><div className="mode-row"><button className={mode==='party'?'selected':''} onClick={()=>setMode('party')}>📺 Party Mode</button><button className={mode==='remote'?'selected':''} onClick={()=>setMode('remote')}>📱 Remote Mode</button></div><p className="fine">{mode === 'party' ? 'Fotos nur auf deinem Gerät; alle stimmen per Handy ab.' : 'Fotos auf allen Geräten; Übertragung über WebRTC.'}</p><button className="button" disabled={busy} onClick={()=>void startHost()}>{busy?'Lobby wird geöffnet …':'SPIEL ERSTELLEN ✨'}</button></div><div className="option"><h2>📲 Mitspielen</h2><p>Zehnstelligen Lobbycode eingeben oder Einladungslink öffnen.</p><label className="field">Lobbycode<input className="code-input" maxLength={200} value={joinCode} onChange={e=>setJoinCode(e.target.value)} placeholder="ABCDE FG234" autoCapitalize="characters" autoComplete="off"/></label><button className="button pink" disabled={busy || !joinCode.trim()} onClick={()=>void startGuest(joinCode)}>{busy?'Verbinde …':'BEITRETEN →'}</button></div></div></div>}
        {role === 'host' && game?.phase === 'lobby' && <div className="panel"><span className="eyebrow">DU BIST HOST 👑</span><h1>Die Lobby</h1><p>Deine Freunde öffnen dieselbe Website und geben diesen Code ein. Nur freigegebene Gäste sehen Spielinhalte. Vergleiche die Prüfkennung mit deinem Freund, bevor du akzeptierst.</p><div className="lobby-code" aria-label={`Lobbycode ${roomCode}`}>{roomCode.slice(0,5)} {roomCode.slice(5)}</div><button className="small" onClick={()=>void copy(roomCode)}>📋 Code kopieren</button><button className="small" onClick={()=>void copy(roomLink(roomCode,location))}>🔗 Einladungslink kopieren</button><section className="admissions" aria-label="Beitrittsanfragen"><h2>🔔 Wer klopft an?</h2>{!requests.length&&<p className="fine">Keine offenen Anfragen. Nur bekannte Personen freigeben.</p>}{requests.map(r=><div className="request" key={r.id}><div><strong>{r.name}</strong><br/><small>Prüfkennung: {r.check}</small></div><button className="button green" onClick={()=>controller.approve(r.id,true)}>Akzeptieren</button><button className="small" onClick={()=>controller.approve(r.id,false)}>Ablehnen</button></div>)}</section><div className="players">{game.players.map(p=><span className="player" key={p.id}>⭐ {p.name}{p.id==='host'?' (Host)':p.connected?'':' · offline'}{p.id!=='host'&&<button className="remove-player" aria-label={`${p.name} entfernen`} onClick={()=>controller.remove(p.id)}>×</button>}</span>)}</div><p>{game.players.filter(p=>p.connected).length}/8 Spieler</p><div className="category-wrap"><h2>Prompt-Kategorien</h2><div className="category-list">{CATEGORIES.map(c=><button key={c} className={categories.includes(c)?'selected':''} onClick={()=>toggleCategory(c)}>{c==='18+'?'🔞 ':''}{c}</button>)}</div><p className="fine">18+ ist standardmäßig aus. Nur mit erwachsenen Mitspielern aktivieren.</p></div><button className="button green" disabled={game.players.filter(p=>p.connected).length<2 || countdown>0 || !categories.length} onClick={beginRound}>{countdown ? `START IN ${countdown} …` : 'RUNDE STARTEN 🚀'}</button></div>}
        {role === 'guest' && !game && <div className="panel center"><span className="eyebrow">VERBINDUNG 📡</span><div className="connecting-face">🛰️</div><h1>{stage==='approval'?'Der Host ist dran!':stage==='connected'?'Spielstand laden …':'Lobby suchen …'}</h1><p>{status}</p>{check&&<p>Deine Prüfkennung: <strong>{check}</strong><br/><small>Diese Kennung muss beim Host neben deinem Namen stehen.</small></p>}<p className="fine">{stage==='approval'?'Freigabe innerhalb von 60 Sekunden.':'Beide Geräte geöffnet lassen. Nach 30 Sekunden endet die Suche.'}</p><button className="small quiet" onClick={leave}>Abbrechen</button></div>}
        {role==='guest' && game?.phase==='lobby' && <div className="panel center"><span className="eyebrow">VERBUNDEN! 🎊</span><h1>Warte auf den Host</h1><p>Du bist als <strong>{me?.name}</strong> dabei. Kein weiterer Code nötig.</p><div className="players">{game.players.filter(p=>p.connected).map(p=><span className="player" key={p.id}>{p.name}</span>)}</div></div>}
        {game && game.phase !== 'lobby' && <div className="panel round"><div className="round-top"><span className="eyebrow">RUNDE {game.round} · {game.category}</span><span className="pill">{game.mode==='party'?'📺 PARTY':'📱 REMOTE'}</span></div><h1 className="prompt">{game.prompt}</h1>
          {game.phase==='submit' && <div className="center"><h2>Such das passende Foto 🔎</h2><p>Wähle ein Bild aus deiner Galerie. Es wird vor dem Senden lokal verkleinert.</p>{!hasSubmitted && !busy && online && <label className="button file-button">📸 FOTO AUSWÄHLEN<input type="file" accept="image/*" onChange={e=>void selectPhoto(e)}/></label>}{busy && <div className="transfer-progress"><p>{status||"Foto wird verarbeitet …"}</p><progress max={100} value={progress} aria-label="Fotoübertragung"/><small>{progress}% · Erfolg erst nach Empfangsbestätigung</small></div>}{hasSubmitted && <p className="success">✅ Foto eingereicht!</p>}<p>{game.photos.length}/{game.players.filter(p=>p.connected).length} Fotos eingereicht</p><p className="fine">Identität der Fotos bleibt bis zum Ergebnis verborgen.</p></div>}
          {game.phase==='vote' && <div><h2>Welches Foto gewinnt? 🗳️</h2><p>{game.mode==='party' && role==='guest' ? 'Schau auf das Gerät des Hosts und wähle die Nummer deines Lieblingsfotos.' : 'Stimm für das lustigste Foto.'} Du kannst dein eigenes Foto nicht wählen.</p>{!remoteReady && <p className="pill">Fotos werden noch übertragen …</p>}<div className={`photo-grid ${game.mode==='party'&&role==='guest'?'party-vote':''}`}>{game.photos.map((photo,index)=><div className="photo-card" key={photo.id}><div className="photo-frame">{(role==='host'||game.mode==='remote') && images[photo.id] ? <img src={images[photo.id]} alt={`Anonymes Foto ${index+1}`}/> : <span>{game.mode==='party'&&role==='guest'?'📺':'⏳'}</span>}</div><strong>FOTO {index+1}</strong><button disabled={voted || busy || !online || photo.ownerId===you || !remoteReady} onClick={()=>vote(photo.id)}>{photo.ownerId===you?'Dein Foto':voted?'Stimme abgegeben':'Dafür stimmen ⭐'}</button></div>)}</div><p className="center">{Object.keys(game.votes).length}/{game.players.filter(p=>p.connected).length} Stimmen · {voted ? 'Deine Stimme ist drin!' : 'Eine Stimme pro Person'}</p></div>}
          {game.phase==='result' && <div className="center"><div className="winner-burst">🏆</div><h2>{winner?.name ?? 'Überraschung'} gewinnt!</h2><p>Ein Punkt für das Foto, das diese Runde gerettet (oder ruiniert) hat.</p><div className="scoreboard">{[...game.players].sort((a,b)=>b.score-a.score).map((p,index)=><div key={p.id}><span>{index+1}. {p.name}{!p.connected?' (offline)':''}</span><strong>{p.score} ⭐</strong></div>)}</div>{role==='host' && <button className="button green" disabled={countdown>0 || game.players.filter(p=>p.connected).length<2} onClick={beginRound}>{countdown?`START IN ${countdown} …`:'NÄCHSTE RUNDE ➜'}</button>}{role==='guest' && <p>Warte auf die nächste Runde …</p>}{role==='host' && <button className="small" onClick={()=>{play('gameover');leave();}}>Spiel beenden</button>}</div>}
        </div>}
        {game?.players.some(p=>!p.connected)&&<div className="connection-warning">Ein Gerät ist offline. Die Runde wartet.{role==='host'&&game.players.filter(p=>!p.connected).map(p=><button className="small" key={p.id} onClick={()=>controller.remove(p.id)}>{p.name} entfernen</button>)}</div>}{!online&&<p className="connection-warning" role="alert">Host nicht erreichbar. Fotos werden gerade nicht gesendet.</p>}{role && <button className="small leave" onClick={leave}>Spiel verlassen ↩</button>}
      </section>}
      {status && game && route==='/spiel' && <div className="toast" role="status">{status}</div>}
      {error && route==='/spiel' && <div className="error" role="alert">⚠️ {error}<button aria-label="Meldung schließen" onClick={()=>controller.clearError()}>×</button></div>}

      {route==='/spiel'&&diagnostic&&<details className="diagnostics"><summary>Verbindungsdiagnose</summary><p>{diagnostic}</p><p className="fine">Nur technische Statusanzeige. Keine IP-Adressen, Fotos oder Verbindungsangebote in Logs.</p></details>}
      {countdown>0&&<div className="countdown-overlay" role="status" aria-live="assertive"><p>Bereit für schlechte Entscheidungen?</p><strong key={countdown}>{countdown}</strong></div>}
    </main><footer><small>Version {BUILD}</small><br/>DELETE THIS! ✦ Fotos nur zwischen euren Geräten ✦ <a href="#/datenschutz">Datenschutz</a></footer>
  </div>;
}
export default App;
