import type { ReactNode } from 'react';
import { ROUND_OPTIONS, type Game, type GameOptions, type GameStyle, type RoundLimit, type RoundStyle } from './game';
export const STYLE_LABELS:Record<GameStyle,string>={CLASSIC:'Klassisch',CUSTOM:'Eigene Prompts',REVERSE:'Reverse',MIX:'Mix'};
const subtitles:Record<GameStyle,string>={CLASSIC:'Eure Packs, eure Fotos',CUSTOM:'Ihr schreibt den Prompt',REVERSE:'Foto zuerst, Text danach',MIX:'Von allem etwas'};
const descriptions:Record<GameStyle,string>={CLASSIC:'Ein Prompt aus euren Packs. Alle suchen ein passendes Foto.',CUSTOM:'Alle schreiben einen Prompt. Einer wird zufällig gewählt und alle suchen ein Foto dazu.',REVERSE:'Jeder reicht ein Foto ein und schreibt zum Foto eines anderen einen lustigen Text. Punkte gehen an die Textautoren.',MIX:'Für jede Runde wird eine eurer ausgewählten Varianten gezogen.'};
type Props={game:Game;disabled:boolean;configure:(s:Partial<GameOptions>)=>void;chooseRounds:(n:RoundLimit)=>void;children?:ReactNode};
export function GameSettings({game,disabled,configure,chooseRounds,children}:Props) {
 return <section className="lobby-settings" aria-label="Partie einstellen">
  <div className="settings-heading"><span className="eyebrow">EURE SPIELREGELN</span><h2>Was geht heute?</h2><p className="fine">Einmal einstellen. Dann einfach spielen.</p></div>
  <fieldset className="round-picker"><legend>Wie viele Runden?</legend>{ROUND_OPTIONS.map(n=><button type="button" key={n} aria-pressed={game.roundLimit===n} disabled={disabled} className={game.roundLimit===n?'selected':''} onClick={()=>chooseRounds(n)}>{n}<span> Runden</span></button>)}</fieldset>
  <fieldset className="style-picker"><legend>Spielmodus</legend><div className="style-grid">{(Object.keys(STYLE_LABELS) as GameStyle[]).map(style=><button type="button" key={style} aria-pressed={game.style===style} className={game.style===style?'selected':''} disabled={disabled} onClick={()=>configure({style})}><strong>{STYLE_LABELS[style]}</strong><span>{subtitles[style]}</span></button>)}</div></fieldset>
  <p className="fine mode-explanation">{descriptions[game.style]}</p>
  {game.style==='MIX'&&<fieldset className="mix-options"><legend>Was kommt in den Mix?</legend>{(['CLASSIC','CUSTOM','REVERSE'] as RoundStyle[]).map(style=><label key={style}><input type="checkbox" checked={game.mixStyles.includes(style)} disabled={disabled||(game.mixStyles.length===1&&game.mixStyles.includes(style))} onChange={e=>configure({mixStyles:e.target.checked?[...game.mixStyles,style]:game.mixStyles.filter(s=>s!==style)})}/>{STYLE_LABELS[style]}</label>)}</fieldset>}
  {children}
  <details className="advanced-settings"><summary>Erweiterte Einstellungen<span aria-hidden="true">+</span></summary><div className="advanced-body">
   <label className="setting-check"><input type="checkbox" checked={game.winnerBonus} disabled={disabled} onChange={e=>configure({winnerBonus:e.target.checked})}/><span><strong>Bonus für den Rundensieg</strong><small>Jede Stimme gibt einen Punkt. Der Sieger erhält zusätzlich +1; bei Gleichstand wird der Bonus ausgelost.</small></span></label>
   <label className="setting-check"><input type="checkbox" checked={game.hideScores} disabled={disabled} onChange={e=>configure({hideScores:e.target.checked})}/><span><strong>Punkte erst im Finale zeigen</strong><small>Die Rundensieger seht ihr sofort. Rangliste und Punktestände bleiben bis zum Schluss geheim.</small></span></label>
   <label className="setting-check"><input type="checkbox" checked={game.reactionsEnabled} disabled={disabled} onChange={e=>configure({reactionsEnabled:e.target.checked})}/><span><strong>Reactions erlauben</strong><small>Lachflash, Applaus und Drama in der Lobby und bei der Foto-Show.</small></span></label>
   {game.reactionsEnabled&&<label className="setting-check"><input type="checkbox" checked={game.reactionSounds} disabled={disabled} onChange={e=>configure({reactionSounds:e.target.checked})}/><span><strong>Sounds für Reactions</strong><small>Kurze Soundeffekte für die ganze Lobby. Der persönliche Stummknopf gilt weiterhin.</small></span></label>}
   <fieldset className="presentation-picker"><legend>Wie läuft die Foto-Show?</legend><div className="segmented"><button type="button" disabled={disabled} aria-pressed={game.autoReveal} className={game.autoReveal?'selected':''} onClick={()=>configure({autoReveal:true})}>Automatisch</button><button type="button" disabled={disabled} aria-pressed={!game.autoReveal} className={!game.autoReveal?'selected':''} onClick={()=>configure({autoReveal:false})}>Manuell</button></div><p className="fine">{game.autoReveal?'Die Fotos erscheinen nacheinander. Die Abstimmung öffnet sich danach automatisch.':'Der Host klickt für jedes Foto auf Weiter und öffnet die Abstimmung.'} Die nächste Runde startet immer der Host.</p></fieldset>
  </div></details>
 </section>;
}
