export const CATEGORIES = ['Normal', 'Freunde', 'Chaos', 'Roast', 'Dating', 'Party', 'Schule', '18+'] as const;
export type Category = typeof CATEGORIES[number];

// Jeder Grundprompt hat drei eigenständige Spielvarianten. 8 × 25 × 3 = 600.
const seeds: Record<Category, string[]> = {
  Normal: [
    'Dieses Bild würde deine Karriere beenden', 'Wenn „wird schon gutgehen“ ein Foto wäre',
    'Kurz bevor alles eskaliert ist', 'Dieses Foto braucht dringend Kontext',
    'Der Moment, in dem der Gruppenchat zum Beweismittel wird',
    'Ein Bild, das man seiner Oma nur mit PowerPoint erklären kann',
    'Die letzte Aufnahme vor einer sehr langen Entschuldigung',
    'Wenn der gesunde Menschenverstand kurz Pause gemacht hat',
    'Ein Foto, das als Entschuldigungsschreiben durchgeht',
    'Hier hat jemand „Ich hab einen Plan“ gesagt',
    'Ein Bild mit der Energie einer unbezahlten Rechnung',
    'Der Grund, warum jetzt eine neue Hausregel existiert',
    'Ein Foto, das mehr Fragen stellt als beantwortet',
    'Wenn dein Schutzengel gerade gekündigt hat',
    'Die offizielle Titelseite deiner schlechten Entscheidungen',
    'Ein Bild, das man aus Versehen dem Chef geschickt hat',
    'Der Moment, in dem „nur ganz kurz“ drei Stunden dauerte',
    'Hier hätte wirklich jemand die Kamera weglegen sollen',
    'Eine Szene, die nach einer PowerPoint über Verantwortung schreit',
    'Wenn ein Dienstag persönlich beleidigend wird',
    'Das letzte Foto vor dem Satz „Sag das bitte niemandem“',
    'Ein Bild, das nach einer Entschuldigung bei der Einrichtung aussieht',
    'Wenn der Algorithmus dich persönlich auslacht',
    'Ein Screenshot aus dem schlechtesten Tutorial der Welt',
    'Ein Foto, das einen unangenehmen Anruf auslöst',
    'Das Profilbild, mit dem jemand auf LinkedIn ein Schneeballsystem verkaufen will',
    'Wenn dein Lebenslauf dieses Foto als Referenz angibt',
    'Ein Bild, das der Algorithmus für „mutig“ und deine Freunde für „bitte löschen“ hält'
  ],
  Freunde: [
    'Der Beweis, warum diese Freundesgruppe keine Aufsicht haben darf',
    'Wenn „wir bleiben heute vernünftig“ als Lüge auffliegt',
    'Das Foto, das im Gruppenchat sofort gelöscht werden sollte',
    'Der Moment, in dem jemand zum schlechten Einfluss befördert wurde',
    'Das Gruppenfoto, auf dem niemand seine Eltern stolz macht',
    'Wenn die Freundschaft durch einen einzigen Blick erklärt ist',
    'Der Beweis, dass ihr euch gegenseitig nicht helfen solltet',
    'Ein Foto aus der Ära „wir waren alle ein Problem“',
    'Wenn jemand „vertrau mir“ sagt und alle trotzdem mitkommen',
    'Ein Bild, das auf einer Hochzeit als Drohung gezeigt wird',
    'Der Moment, in dem eine Freundschaft teuer wurde',
    'Wenn einer filmt, statt Erste Hilfe für die Würde zu leisten',
    'Das Foto, das die Eltern im Familienchat nie sehen dürfen',
    'Euer inoffizielles Bewerbungsgespräch für eine Realityshow',
    'Der Grund, warum eure Ausflüge jetzt genehmigt werden müssen',
    'Wenn der einzig Vernünftige auch schon aufgegeben hat',
    'Ein gemeinsames Foto mit individuellen Ausreden',
    'Das Bild, bei dem alle gleichzeitig „Du warst das!“ rufen',
    'Wenn aus „ein kurzes Treffen“ ein Mythos wird',
    'Das Freundschaftsfoto mit Kündigungsgrund im Hintergrund',
    'Ein Bild, das euren WhatsApp-Namen rechtfertigt',
    'Wenn die gemeinsame Gehirnzelle Urlaub nimmt',
    'Der Moment, in dem ein Insider-Witz zu weit ging',
    'Ein Foto, das nur eure Gruppe lustig findet – leider zu Recht',
    'Wenn Freundschaft bedeutet, gemeinsam die falsche Tür zu öffnen'
  ],
  Chaos: [
    'Das Foto, das fünf Sekunden vor dem Feueralarm entstand',
    'Wenn ein Toaster die Kontrolle über den Abend übernimmt',
    'Der Moment, in dem Plan B ebenfalls explodiert',
    'Ein Bild mit der Energie eines Einkaufswagens auf Glatteis',
    'Wenn eine Zimmerpflanze zur Hauptverdächtigen wird',
    'Der Anfang einer Pressekonferenz ohne gute Antworten',
    'Ein Foto, das wie ein Versicherungsfall riecht',
    'Wenn das Universum „Überraschung!“ schreit und wegrennt',
    'Der Grund, warum der Nachbar jetzt ein Tagebuch führt',
    'Wenn ein Luftballon eine ganze Freundesgruppe besiegt',
    'Ein Bild, das rückwärts immer noch keinen Sinn ergibt',
    'Die Ruhe unmittelbar vor dem Nudelsieb-Zwischenfall',
    'Wenn die Sicherheitsanweisung als Vorschlag verstanden wurde',
    'Ein Foto aus einer Parallelwelt mit noch schlechteren Entscheidungen',
    'Der Moment, in dem sogar der Hund enttäuscht aussieht',
    'Wenn ein harmloser Stuhl plötzlich Bossgegner wird',
    'Das letzte Bild, bevor die Küche offiziell zur Baustelle wurde',
    'Ein Foto, das „Wir können das erklären“ unmöglich macht',
    'Wenn die Physik heute einfach keine Lust hatte',
    'Der Moment, in dem Konfetti zum strukturellen Problem wird',
    'Ein Bild wie der letzte Level eines Baumarkts',
    'Wenn „einfach draufdrücken“ keine Reparaturmethode war',
    'Das Chaos, das mit einem einzigen Teelöffel begann',
    'Ein Foto, das ein sehr verwirrter Feuerwehrmann beschreiben müsste',
    'Wenn die Realität kurz zur schlecht geschnittenen Sitcom wird'
  ],
  Roast: [
    'Ein Foto mit der Ausstrahlung einer PowerPoint-Folie von 2006',
    'Wenn Selbstbewusstsein deutlich schneller war als Kompetenz',
    'Das Bild, das deine Frisur vor Gericht bringen würde',
    'Ein Outfit mit eigenem Krisenstab',
    'Wenn eine Pose einen öffentlichen Widerruf verdient',
    'Ein Foto, das „Ich bin sehr spontan“ unangenehm bestätigt',
    'Der Beweis, dass Geschmack kein Pflichtfach ist',
    'Wenn die Kamera versucht hat, höflich wegzuschauen',
    'Ein Bild mit der Energie eines motivierenden LinkedIn-Posts',
    'Wenn jemand die Hauptrolle wollte und Statist wurde',
    'Das Foto, das dein zukünftiges Ich verklagen wird',
    'Ein Styling, das drei Freundschaften überlebt hat',
    'Wenn „Das steht mir“ nie überprüft wurde',
    'Ein Bild, das selbst die Autokorrektur korrigieren möchte',
    'Der Moment, in dem Coolness Hausverbot bekam',
    'Wenn dein Gesichtsausdruck eine schlechte Bewertung abgibt',
    'Ein Foto, das „Ich war mal jung“ nicht ausreichend entschuldigt',
    'Wenn die Selbstdarstellung den Kontakt zur Realität verliert',
    'Ein Look mit mehr Selbstvertrauen als Stoff',
    'Das Bewerbungsgespräch für den Titel „Peinlichster Nebencharakter“',
    'Ein Bild, bei dem sogar die Filterfunktion streikt',
    'Wenn „lässig“ eine formelle Beschwerde einreicht',
    'Der Beweis, dass man nicht jeden Winkel ausprobieren muss',
    'Ein Foto mit der Energie eines Motivationsplakats im Keller',
    'Wenn dein Alter Ego lieber anonym bleiben möchte',
    'Das Foto, das du im Lebenslauf als „kreative Problemlösung“ verkaufen würdest',
    'Ein Bild, bei dem sogar dein LinkedIn-Netzwerk „weniger anzeigen“ klickt',
    'Wenn die Kamera höflich war und trotzdem Anzeige erstattet'
  ],
  Dating: [
    'Das Foto, bei dem die Dating-App eine Sicherheitsfrage stellt',
    'Wenn das erste Date nach einer Fluchtmöglichkeit sucht',
    'Ein Bild, das „Ich bin eigentlich ganz normal“ widerlegt',
    'Der Moment, in dem aus Flirten eine Fallstudie wurde',
    'Ein Profilfoto mit erstaunlich vielen offenen Fragen',
    'Wenn die Chemie stimmt, aber die Kulisse kündigt',
    'Das Bild, das du erst nach dem dritten Date zeigen solltest',
    'Wenn dein Wingman die Situation unabsichtlich verschlimmert',
    'Ein Foto, das auf Hinge unter „red flag“ stehen könnte',
    'Der Moment, in dem eine romantische Geste baulich scheitert',
    'Wenn du „Ich bin unkompliziert“ sagst und dieses Bild existiert',
    'Das Date, das danach eine Gruppenbesprechung brauchte',
    'Ein Bild mit der Energie einer katastrophalen Sprachnachricht',
    'Wenn die Ex das Foto ohne Kommentar liked',
    'Der Grund, warum „spontaner Spaziergang“ jetzt verdächtig klingt',
    'Ein Profilbild, das deine Mutter aus Versehen auswählt',
    'Wenn das Kennenlernen zur absurden Castingrunde wird',
    'Ein Foto aus der Kategorie „War das ein Date?“',
    'Der Moment, in dem Charme eine Pause brauchte',
    'Wenn du „Ich kann kochen“ zu früh behauptet hast',
    'Das Bild, das nach einem peinlichen Doppeldating verlangt',
    'Wenn eine Rose die falsche Person überzeugt hat',
    'Ein Foto, bei dem „lass uns Freunde bleiben“ schon im Raum steht',
    'Der Moment, in dem Smalltalk eine Notlandung macht',
    'Wenn aus „Netflix und chillen“ ein WLAN-Störungsticket wird'
  ],
  Party: [
    'Das letzte seriöse Foto dieser Party',
    'Wenn der DJ dich persönlich beleidigt und du trotzdem tanzt',
    'Der Moment, in dem ein Plastikbecher zum Hauptdarsteller wurde',
    'Ein Bild, das nach einer entschuldigenden Nachricht an die Nachbarn klingt',
    'Wenn die Playlist die Kontrolle über die Gäste übernimmt',
    'Der Beweis, dass die Garderobe auch eine Nebengeschichte hatte',
    'Ein Foto aus der Phase „Es ist doch erst neun“',
    'Wenn jemand „Eine Runde noch“ zum vierten Mal sagt',
    'Das Bild, das am nächsten Morgen nur mit Sonnenbrille erträglich ist',
    'Wenn die Fotobox plötzlich zum Verhörraum wird',
    'Der Moment, in dem die Deko unerwartet zurückschlägt',
    'Ein Foto mit der Energie einer verlorenen Jacke',
    'Wenn die Hausparty zur sehr kleinen Stadtratssitzung wird',
    'Ein Bild, das auf keinen Fall die Einladung illustrieren sollte',
    'Der Beweis, dass Konfetti eine langfristige Entscheidung ist',
    'Wenn die Tanzfläche ein eigenes Haftungsformular braucht',
    'Das Foto unmittelbar vor „Wer kennt diese Person?“',
    'Wenn das Buffet zum sozialen Experiment wird',
    'Ein Bild, das der Gastgeber in einer Woche noch findet',
    'Der Moment, in dem Karaoke zur internationalen Krise wurde',
    'Wenn eine Geburtstagstorte die Runde gewinnt',
    'Ein Foto, das nach drei verpassten Anrufen aussieht',
    'Wenn der letzte Bus zur Legende wird',
    'Das Bild, das den Satz „kleine Feier“ widerlegt',
    'Wenn der Abend mit einem dramatischen Türschild endet'
  ],
  Schule: [
    'Das Foto, das in der Klassenfahrt-Präsentation zensiert wird',
    'Wenn Gruppenarbeit eigentlich Einzelhaft mit Zeugen ist',
    'Der Moment, in dem das Referat den Raum verlassen wollte',
    'Ein Bild, das „Der Drucker war schuld“ glaubwürdig macht',
    'Wenn die Schulglocke wie eine Rettungsmission klingt',
    'Der Beweis, dass die Projektwoche selbst Hilfe brauchte',
    'Ein Foto aus der Ära „Wir haben eh noch Zeit“',
    'Wenn das Klassenzimmer aussieht wie nach einer Talkshow',
    'Das Bild, das nicht ins Jahrbuch darf – also genau dort landet',
    'Wenn die PowerPoint mehr Übergänge als Fakten hat',
    'Der Moment, in dem alle so tun, als hätten sie gelernt',
    'Ein Foto, das dem Schulsprecher eine Pressekonferenz beschert',
    'Wenn der Wandertag zur Expedition ohne Karte wird',
    'Das Gruppenprojekt mit fünf Namen und einem arbeitenden Menschen',
    'Ein Bild, bei dem sogar die Kreide enttäuscht ist',
    'Wenn die Vertretungsstunde zur improvisierten Republik wird',
    'Das Foto direkt vor einer sehr langen Durchsage',
    'Wenn der Sitzplan einen diplomatischen Zwischenfall auslöst',
    'Ein Bild, das ein mündliches „Erklären Sie das“ verdient',
    'Wenn aus einem Pausenbrot eine Klassenlegende wird',
    'Der Moment, in dem der Taschenrechner innerlich kündigt',
    'Ein Foto mit der Energie eines vergessenes Hausübungshefts',
    'Wenn die letzte Schulwoche plötzlich zum Actionfilm wird',
    'Das Bild, bei dem die Lehrkraft nur noch tief einatmet',
    'Wenn der Elternabend eine unerwartete Beweisaufnahme wird'
  ],
  '18+': [
    'Das Foto, das nur im Erwachsenen-Gruppenchat überlebt',
    'Wenn das Date plötzlich eine Haftungsausschlusserklärung braucht',
    'Ein Bild, das nach einer Nachricht um 3:47 Uhr aussieht',
    'Der Beweis, dass „nur noch ein Drink“ keine Zeitangabe ist',
    'Wenn der Morgen danach ein Ermittlungsverfahren eröffnet',
    'Das Foto, das deine Ex ausgerechnet beim Brunch sieht',
    'Ein Bild mit der Energie einer sehr schlechten Anmache',
    'Wenn das Hotelpersonal höflich keine Fragen stellt',
    'Der Moment, in dem der Flirt den letzten Bus verpasst',
    'Ein Foto aus der Kategorie „Darüber reden wir nüchtern“',
    'Wenn ein Junggesellenabschied zur diplomatischen Krise wird',
    'Das Bild, das am nächsten Tag im Büro zur Legende wird',
    'Wenn die Afterparty mehr Geheimnisse als Gäste hat',
    'Ein Foto, das nur mit zwei Espresso erklärt werden kann',
    'Der Beweis, dass die letzte Runde die erste schlechte Idee war',
    'Wenn die Dating-App ein Verfallsdatum für Nachrichten bräuchte',
    'Das Bild, bei dem das Taxi schneller fahren sollte',
    'Wenn „wir sind erwachsen“ als Sachbeschädigung am Ruf endet',
    'Ein Foto mit der Energie einer peinlichen Hochzeitsrede',
    'Der Moment, in dem die Hausbar zum Tatort der Würde wird',
    'Wenn die Ex, der Chef und der Barkeeper gleichzeitig auftauchen',
    'Ein Bild, das nach zwei Tagen Kater immer noch Fragen aufwirft',
    'Wenn der Heimweg länger dauert als die Beziehung',
    'Das Foto, das bei einer Wohnungsbesichtigung nicht gezeigt wird',
    'Wenn aus „Bleib noch kurz“ ein kompletter Sonntag wird'
  ]
};

export const PROMPTS: Record<Category, string[]> = Object.fromEntries(
  CATEGORIES.map(category => [category, seeds[category].flatMap((seed, i) => [
    `${seed}.`,
    `${seed} – und die Erklärung macht es nur schlimmer.`,
    `${seed} – ${['niemand übernimmt dafür Verantwortung', 'eine Person lacht noch immer darüber', 'das bleibt bitte unter uns', 'es gab danach eine neue Hausregel', 'der Gruppenchat hat Beweise'][i % 5]}.`
  ])])
) as Record<Category, string[]>;

export function pickPrompt(categories: Category[], used: string[], random = Math.random): { category: Category; text: string } {
  const pool = categories.flatMap(category => PROMPTS[category].map(text => ({ category, text })));
  if (!pool.length) throw new Error('Wähle mindestens eine Kategorie.');
  const fresh = pool.filter(item => !used.includes(item.text));
  const choices = fresh.length ? fresh : pool;
  return choices[Math.floor(random() * choices.length)];
}
